### PR TITLE
Support Overview

### PR DESCRIPTION
**Pull request by dcstlouis**
Ongoing work for SupportOverview component, outlined in #256 and #360

### CODE REVIEW

**Comment by c-simpson** [comment]
@dcstlouis API endpoint for this in #404

**Comment by jwtruver** [comment]
incorporate the data Cris created in the api into the front end. @dcstlouis will tackle this.

**Comment by c-simpson** [comment]
This looks great!

**Comment by c-simpson** [comment]
Handling rfm data from support endpoint:

Check 'number_of_gifts'. If  **number_of_gifts** is 0, *STOP* , other fields may not exist. If they do, they'll have no data.

If > 0 and  matching_id associated with a sfcontactid, 1+ gifts: 
```
rfm_color :  "#990000"
rfm_label :  "High impact, slipping"
rfm_score : "453"
rfm_text_color : "#ffffff"
```

**Comment by c-simpson** [comment]
@dcstlouis  Pushed rfm code. See comments

**Comment by dcstlouis** [comment]
Updated the Support Overview so it now includes the RFM score and only displays data if it exists.

**Comment by c-simpson** [comment]
This looks great!  
One last suggestion, if you felt like it and it wasn't a pain,  you could  use the **rfm_color** and **rfm_text_color** to color the RFM Category line. But I think this is ready to go either way.

**Comment by dcstlouis** [comment]
Great minds! Code for that is on line 48 of the SupportOverview component, but let me know if it's not working properly

**Comment by c-simpson** [comment]
image

I never see  `(data.rfm_color)` defined.   Do you want `row.rfm_color` ?

**Comment by dcstlouis** [comment]
Nice catch, thanks! Fixed!

**Pull request merged**
