### PR TITLE
Fixed a crash when phone numbers are 1 character long

### LINKED ISSUE #184: 500: "The string supplied did not seem to be a phone number."
When running the code merged in #176 , 
Got `phonenumbers.phonenumberutil.NumberParseException` when executing these uploaded files:

> shelterluvpeople.xlsx
> Volgistics_All volunteer information (stock).xlsx
> Salesforce_PAWS Donation (all Time) (excel).xlsx

```
paws-compose-server |   File "/app/datasource_manager.py", line 87, in normalize_phone_number
paws-compose-server |     parsed_number = phonenumbers.parse(number, "US")
paws-compose-server |   File "/usr/local/lib/python3.7/site-packages/phonenumbers/phonenumberutil.py", line 2845, in parse
paws-compose-server |     "The string supplied did not seem to be a phone number.")
paws-compose-server | phonenumbers.phonenumberutil.NumberParseException: (1) The string supplied did not seem to be 
a phone number.
```

### PR DESCRIPTION
**Pull request by mtdamert**
Should fix #184

### CODE REVIEW

**Comment by mtdamert** [comment]
The phone number library usually ignores bad phone numbers. The exceptions in the latest data are when a phone number is one digit long or when it's [], which this code fixes

**Comment by c-simpson** [comment]
Mike,
It looks like this would pass '1234 Jones St' to the parsing library (which could happen if data gets placed in wrong columns).

I tried my hand writing a test with some test cases (attached). See if it's useful. (Can't attach a .py file, so it's got txt extension.)

[checknum.txt](https://github.com/CodeForPhilly/paws-data-pipeline/files/5962949/checknum.txt)

**Comment by mtdamert** [comment]
Cris,
That's a good idea to look for data in the wrong column.
In the Salesforce data, I also see hyphens, spaces, and parentheses. I wonder if a regex is the way to go.

I'll be away from a computer for the next couple days, but can get back to this next week.

**Comment by c-simpson** [comment]
Mike,   I sent you an updated function via Slack. Any objection to merging it before the demo and them coming back?

Enjoy your downtime!

**Comment by mtdamert** [comment]
Cris, I think we're close but not quite there. It looks like checking for a number with string.isdigit() will return false if there are parentheses or hyphens in the phone number. So the phone number `(123) 456-7890` would not be loaded to our database with the latest you sent me.

Thanks, and take care

**Comment by c-simpson** [comment]
Ha! Will have another go. Thanks!

**Comment by c-simpson** [comment]
Had some more thoughts on this - see #189

**Comment by mtdamert** [comment]
I uploaded a new version that I think catches all the cases we discussed. It ran successfully when I tested.
For now it uses the print() function to put invalid phone numbers in the console. It should be possible to write the invalid phone numbers to the database in the future

**Comment by c-simpson** [comment]
Mike, I think you have caught all the cases.  Two thoughts:  
 - This might be cleaner than the `if` block:  `number = re.sub('[() -.]', '', number)`
 -  Instead of doing the `format_number()` step, would it make sense to just return  `parsed_number.national_number` for the DB  and do the formatting in the UI? (as in #189)

**Pull request merged**
