### PR TITLE
fixes and changes for nginx

### PR DESCRIPTION
**Pull request by urirot**
forward requests to index.html (fixes refresh on pages that are not home page)
change /upload to /admin

### CODE REVIEW

**Comment by urirot** [comment]
- added workers to uwsgi - can that help with our async issues? I think we can load balance using this and maybe block more than one execute etc. what do you think? I might be completely off... @dkelley @c-simpson 
- forward requests to index.html (fixes refresh on pages that are not home page)
- change /upload to /admin

**Comment by c-simpson** [comment]
I had done the experiment adding workers and that will let you have P (# processes)  outstanding requests (_e.g_., `/api/execute `and /`api/get_execution_status/<job_id>`  [see last image in #232]*   ) but, as I was saying last night, the two processes aren't seen as distinct by Postgres/SQLA, leading to the db log messages about already/not being in a transaction. This is due to SQLAlchemy's connection pooling model - when the `with` ends without a COMMIT, SQLA issues a ROLLBACK before returning the connection to the pool. If there's another transaction open, you have problems. 

If there's a way to ensure distinct connection pools, we may have a way forward in this direction.

  * I'm less optimistic now than I was.

**Comment by c-simpson** [comment]
I'm going to dig into this: https://docs.sqlalchemy.org/en/14/core/pooling.html#pooling-multiprocessing

**Comment by c-simpson** [comment]
The engine.dispose() trick seems to work and gets a new (distinct) DB connection, so execute() does not affect the stats functions.   I'm going to write up a proposal tonight for how to handle.

**Comment by c-simpson** [comment]
Committed changes (https://github.com/CodeForPhilly/paws-data-pipeline/pull/240/commits/49533e06baf216b11affad0c342a09a689fb074b) to support getting the execution status while running.   
When record matching starts, look for the line like   

`INFO in match_data: ***** Running execute job ID 1616703314 ***** `

Then use that value to get execution status:
`http://localhost:5000/api/get_execution_status/1616703314`

That status get updated with the ' Matching rows 1-4745 of 94907 ' log messages. We may want to have that update more often.

I think I'm going to do a new table format that has

job_id | status | progress
--|--|--

to simplify searching by status.

**Review by c-simpson — APPROVED** [review]
I'm still seeing 'Last Updated' and 'Last Analysis' times as UTC. 'Last Analysis' comes from DB (Last Execution Time) which I'm storing as UTC.  

Seems like we should store all as UTC and set local time in UI. Thoughts?  Otherise we need to make sure TZ is set to America/New_York in containers.

**Pull request merged**
