### PR TITLE
Volshifts insert

### PR DESCRIPTION
**Pull request by c-simpson**
This builds on PR #382 .

Following 382, it does direct import into the `volgisticsshifts` table. 
There's some clean up for changed column names:
`volgisticsshifts.number` -> `.volg_id`
`volgisticsshifts.from`  - > `.from_date`

Removes Fosters block from 360View as per KF

@sposerina  Please review `datasource_manager.py`   - Looks correct after changes?  Table mappings get used by `clean_and_load_data.py` - would it be better to feed c&l a list instead of it collecting tables from DB?

### CODE REVIEW

**Comment by c-simpson** [comment]
@dcstlouis   I made some edits to UI stuff. If you have time, can you make sure I didn't mess up anything?

**Review by dcstlouis — APPROVED** [review]
Front-end changes look good to me!

**Comment by sposerina** [comment]
@c-simpson Since the importers are now handling the data load, the keys `volgisticsshifts` and `salesforcedonations` keys are probably no longer necessary in the `CSV_HEADERS` and `DATASOURCE_MAPPING` dictionaries located in `datasource_manager.py'
Should be tested first.

**Comment by c-simpson** [comment]
@sposerina That's what I thought, but `__clean_raw_data(df, table_name)` gets a KeyError if they don't exist.  (See 'removed comments' commits above.)  Maybe we should create an explicit list of tables to feed to 
https://github.com/CodeForPhilly/paws-data-pipeline/blob/bd98de8de1c42615dc3ba649b7082fffeee6d05d/src/server/pipeline/clean_and_load_data.py#L31

**Comment by c-simpson** [comment]
Merge 382 first!

**Pull request merged**
