### PR TITLE
Issue #327: VolunteerHistory and Donations show most recent 3

### PR DESCRIPTION
**Pull request by dcstlouis**
- [x] Donations data: should be ordered by most recent; change "Top 3" to "Most recent 3"
- [x] Volunteer history: should also be showing most recent 3 (not unique 3); change the "Top 3" to "Most recent 3"
- [x] Clicking on shelterluv link should open in new window (this was already done)

### CODE REVIEW

**Comment by c-simpson** [comment]
@dcstlouis   On contact TT (840), the dates in the Volunteer History list alternate every 1/2 second or so between 'Unknown' and 'Invalid date', so the Assignments list bounces right and left.

Same contact, SL link gets a 404 - are we using the right ID?

**Comment by kfettich** [comment]
The SL link for multiple people got a 404 error for me earlier today; looks
like SL links that work use a short ID, while we use a long ID. Not sure if
something changes on their end, or on ours.

**Comment by dcstlouis** [comment]
@c-simpson I pushed a change that filters out all shifts with "invalid date", which should resolve the issue you were seeing.

Regarding the SL links: I'm not sure where the short IDs are coming from. The long IDs are from the SL API.

**Review by c-simpson — APPROVED** [review]
Thanks!

**Pull request merged**
