### PR TITLE
Create RFM tables (390)

### PR DESCRIPTION
**Pull request by c-simpson**
Creates `rfm_scores`  and `rfm_mapping` tables.

The script in `src/server/alembic/populate_rfm_mapping.sql` can be used to populate the mapping table (now with default values, later with real ones when available).

For #390

### CODE REVIEW

**Comment by c-simpson** [comment]
@bdeck8317     Here's what the `rfm_edges` table looks like. If you can store your edge records as dicts, we can do json.dumps()  and json.loads()  to store and pull/load from the DB.

```
component |   edge_string                                          |
----------+--------------------------------------------------------+
r         | {"1": 14, "2": 67, "3": 419, "4": 676, "5": 989}       |
f         | {"1": 32, "2" : 97, "3" : 145, "4" : 167, "5" : 212}   |

**Comment by bdeck8317** [comment]
@c-simpson okay, I finished the function that does this for us. `SFDC-Playground/Python_Code/rfm_funcs/edges_dicts.py`

**Comment by c-simpson** [comment]
That 285 branch is ancient.   How about creating a new branch from master and adding rfm_funcs as a peer to /src/server/api ?

**Comment by bdeck8317** [comment]
@c-simpson  should i just leave the old branch as is?

**Comment by c-simpson** [comment]
@bdeck8317   Yes, we need to do a house-cleaning at some point.

**Comment by bdeck8317** [comment]
@c-simpson i have the edges as dicts now, how do you recommend I pass this off to you?

**Comment by c-simpson** [comment]
@bdeck8317  Feed the dicts to json.dumps() and send me the resulting strings

**Comment by bdeck8317** [comment]
@c-simpson 

`
recency json: '{"5": 262, "4": 1097, "3": 1910, "2": 2851, "1": 4749}'
frequency json: '{"1": 0, "2": 1, "3": 2, "4": 3, "5": 4}'
monetary json: '{"1": 0.0, "2": 50.0, "3": 75.0, "4": 100.0, "5": 210.0}'
`

**Comment by c-simpson** [comment]
@bdeck8317    Instead of having three dictionaries, let's group them together into one:
```
rfm = { 'r' : r , 'f' : f , 'm' : m}

Then you can do things like:
>>> rfm['r']
{'5': 262, '4': 1097, '3': 1910, '2': 2851, '1': 4749}  

>>> rfm['r']['4']
1097  
```
That lets us use the existing k/v table and I'll give you a `load_rfm()` and a `write_rfm()` .  Does that work?

**Comment by bdeck8317** [comment]
@c-simpson  yeah that works. I'll send in a few

**Pull request merged**
