### PR TITLE
Donations section now shows most recent 3 donations

### PR DESCRIPTION
**Pull request by dcstlouis**
Resolves issue #353 by sorting by `close_date`

### CODE REVIEW

**Comment by c-simpson** [comment]
With PR #366 , donation dates will now be coming from the DB as full timestamps: `Fri, 04 Jun 2021 00:00:00 GMT` . Ummm... @sposerina - Any idea how that gets generated from the nice simple '2021-06-04' in the DB?

@dcstlouis , see #pdp_private for Contact name . This person has lots of recurring donations but the last one is shown twice. (So I see 6/4, 6/4, 5/4) but only a single 6/4 is delivered from the view 360 call.

**Comment by sposerina** [comment]
Do we want these as timestamps? I thought Date was a more proper datatype as the time portion probably doesn't hold much significance.

**Comment by c-simpson** [comment]
@dcstlouis  There actually ARE multiple 6/4 records in DB.   @sposerina What happens if you uploaded the same file twice?

WRT the first issue, the values come back from the DB as a `datetime.date`. I suspect that it's the `jsonify` step  that converts them to e.g., "Fri, 04 Jun 2021 00:00:00 GMT".  The query is `"select * from salesforcedonations ...` so I think the best idea would be to do an explicit query for the fields we care about (close_date, amount, type, and primary_campaign_source ?) and cast the close_date to text. I can do that if it makes sense.

**Comment by sposerina** [comment]
>  What happens if you uploaded the same file twice?
`df = old_data.append(df, ignore_index=True).drop_duplicates()` It will drop the duplicates

**Comment by c-simpson** [comment]
https://github.com/CodeForPhilly/paws-data-pipeline/pull/364/commits/f77bb095e45c299855cabc94a9a21f13bc4210d9  returns the date as a text string in YYYY-MM-DD format and the UI seems happy about it. Please test!

**Comment by sposerina** [comment]
LGTM

**Pull request merged**
